# Site settings
title: Rey Pham
header-img: img/home-bg.jpg
email: pea5137@gmail.com
description: Rey Pham
baseurl: ""
url: "http://rey5137.com"
timezone: Asia/Saigon
twitter_username: rey5137
github_username: rey5137
google_plus_username: reypham
linkedin_username: rey-pham/74/904/167

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:categories/:title
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# Plugins
gems:
  - jekyll-sitemap
